// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCZMIrQ51ukZOkw8YvqH2muf2IdDG6TorA',
//     appId: '1:664406668538:web:d144987dd0d11fc0130543',
//     messagingSenderId: '664406668538',
//     projectId: 'carfy-34d1a',
//     authDomain: 'carfy-34d1a.firebaseapp.com',
//     storageBucket: 'carfy-34d1a.firebasestorage.app',
//     measurementId: 'G-DPZ1EJQHC9',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDjsloNd4i2Vc0mTG1uMVUYFsrR8PZUwYA',
//     appId: '1:664406668538:android:6ef70259d0a24ac8130543',
//     messagingSenderId: '664406668538',
//     projectId: 'carfy-34d1a',
//     storageBucket: 'carfy-34d1a.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAavsHTyWwu4hlwh0ds8wOI22oG-i-51s0',
//     appId: '1:664406668538:ios:7e66a39a367e9859130543',
//     messagingSenderId: '664406668538',
//     projectId: 'carfy-34d1a',
//     storageBucket: 'carfy-34d1a.firebasestorage.app',
//     iosBundleId: 'com.example.cfy',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAavsHTyWwu4hlwh0ds8wOI22oG-i-51s0',
//     appId: '1:664406668538:ios:7e66a39a367e9859130543',
//     messagingSenderId: '664406668538',
//     projectId: 'carfy-34d1a',
//     storageBucket: 'carfy-34d1a.firebasestorage.app',
//     iosBundleId: 'com.example.cfy',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCZMIrQ51ukZOkw8YvqH2muf2IdDG6TorA',
//     appId: '1:664406668538:web:d6776e8e157ebac9130543',
//     messagingSenderId: '664406668538',
//     projectId: 'carfy-34d1a',
//     authDomain: 'carfy-34d1a.firebaseapp.com',
//     storageBucket: 'carfy-34d1a.firebasestorage.app',
//     measurementId: 'G-MWZKZ46YFV',
//   );
// }
